name: Run Gradle Tests

run-name: Run Graddle Tests on ${{ github.repository }}

on: [ push ]

jobs:
  Run-Gradle-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository is ${{ github.repository }}."
      - run: echo "Branch is  ${{ github.ref }}."
      - run: echo "User is ${{ github.actor }}."
      - run: echo "Trigger action is ${{ github.event_name }}."

      - name: Check repository  ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        run: cd ${{ github.workspace }} && ./gradlew build

      - name: Ensure app is compiled
        run: echo "ls ${{ github.workspace }}/build/libs/"
