name: Run Gradle Tests

run-name: Run Graddle Tests on ${{ github.repository }}

on: [ push ]

jobs:
  Run-Gradle-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Repository is ${{ github.repository }}."
          echo "Branch is ${{ github.ref }}."
          echo "User is ${{ github.actor }}."
          echo "Event is ${{ github.event_name }}."

      - name: Check out repository ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: 'x64'
          server-id: 'github'
          settings-path: ${{ github.workspace }}

      - name: Build with Gradle
        run: |
          cd ${{ github.workspace }}
          ./gradlew build

      - name: Test with Gradle
        run: |
          ./gradlew test

      - name: Ensure app is compiled
        run: ls ${{ github.workspace }}/build/libs/

      - run: echo "Job finished. The status is ${{ job.status }}."