name: Test Chained Jobs

run-name: Test Chained Jobs on branch ${{ github.ref }} on repository ${{ github.repository }}

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  job-1-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job-1-1..."
      - run: echo "job-1-1 finished!"

  job-1-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job-1-2..."
      - run: echo "job-1-2 finished!"

  job-1-3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job-1-3..."
      - run: echo "job-1-3 finished!"

  job-2-1:
    runs-on: ubuntu-latest
    needs: [ job-1-1, job-1-2, job-1-3 ]
    steps:
      - run: echo "Running job-2-1..."
      - run: echo "job-2-1 finished!"

  job-2-2:
    runs-on: ubuntu-latest
    needs:
      - job-1-1
      - job-1-2
      - job-1-3
    steps:
      - run: echo "Running job-2-2..."
      - run: echo "job-2-2 finished!"

  job-3-1:
    runs-on: ubuntu-latest
    needs: [ job-2-1, job-2-2 ]
    steps:
      - run: echo "Running job-3-1..."
      - run: echo "job-3-1 finished!"
